# Generated by Django 5.2.14 on 2026-05-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название страницы"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на картинку",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент страницы",
                "verbose_name_plural": "Контент страниц",
            },
        ),
    ]
