# Generated by Django 5.2.14 on 2026-05-27 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swimming", "0002_pagecontent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagecontent",
            options={},
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Категория"
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
    ]
